### ISSUE TITLE
Add pip setup.py

### ISSUE THREAD

**Issue by oschwengers** [BolognaBiocomp/deepsig#15]
Hello, thanks for providing DeepSig - a wonderful and open alternative to SignalP!

However, it is not available via PyPI or Conda which unfortunately decreases its overall usability.

Hence, might it be possible to add a pip-conform `setup.py` to this repository (along with potentially required changes) and upload it to https://pypi.org?

By doing so, it would also be straightforward to create a related bioconda package. Thanks in advance best regards!

**Comment by oschwengers** [comment]
I've tried to come up with a first solution:
#16

**Comment by savojard** [comment]
Hello @oschwengers ! I finalized the upload on pypi:

https://pypi.org/project/deepsig-dist/0.9/

I had to use deepsig-dist since the name deepsig was already taken.
We will fix README issues after we have the package on bioconda. 
Thank you and sorry for being late in accepting your PR.

**Comment by oschwengers** [comment]
Hi @savojard ,
thanks for merging the PR. Unfortunately, I cannot access (HTTP 404) the PyPI repository you've mentioned: https://pypi.org/project/deepsig-dist.

Could you please check, if the repo is online and public?

**Comment by savojard** [comment]
Hi @oschwengers,

sorry but I had to remove the PyPI repo because of problems in the installation of dependencies. I'm working on it and I'll let you when the repo is ready. 
Sorry for that.
Thank you

Cas

**Comment by savojard** [comment]
Hi
this is the link to PyPI repo:

https://pypi.org/project/deepsig-biocomp/0.9/

I had to change a bit setup.py (importing deepsig module there didn't work during package building). 
Please, do some testing on a clean environment.
Best,

Cas

**Comment by oschwengers** [comment]
awesome and thanks for sharing. I'll start to work on the conda package next week.

**Comment by oschwengers** [comment]
I forgot to mention, in order to create a conda package we also need a proper Git release.
Could you therefor create a proper `v1.0` release for this DeepSig repo?
