### ISSUE TITLE
More CPUs used than specified via --threads

### ISSUE THREAD

**Issue by oschwengers** [BolognaBiocomp/deepsig#28]
Hi @savojard ,
I benchmarked version 1.2.3 to find the sweatspot in terms of provided threads. Unfortunately, deepsig uses *all* available CPUs on a given machine during the signal peptides detection step. The cleavage site detection seems to work as expected.

For example executing deepsing with `--threads 8` still used 8 CPUs which was the max on this machine.
This will result in very problematic situations if multiple processes of deepsig run in parallel, e.g. on an HPC systems. Could you please try to fix this behavior?

**Comment by oschwengers** [comment]
Sry, I just recognized that the above numbers are of course wrong and misleading.

On a machine with 8 cores I executed DeepSig with `--treads 4`. Unfortunately, DeepSig still allocates 8 threads and uses all 8 cores for the signal peptide detection step. `biocrf-static` works as expected with a max of 4 threads in this case. Any ideas how to fix that?

**Comment by savojard** [comment]
Hi @oschwengers 

Setting Tensorflow parallelism is not a trivial task. However, I attempted a fix and drafted a new release 1.2.4.
Please, let me know if its working.
Thank you!

**Comment by oschwengers** [comment]
Hi @savojard ,
yes, it works like a charm now (installed via Conda). Thanks a lot!
