### ISSUE TITLE
Versions out of sync

### ISSUE THREAD

**Issue by oschwengers** [BolognaBiocomp/deepsig#29]
The version (`__version__= '1.2' `) specified in `__init__.py` is out of sync with the GitHub release (`1.2.3`) as well as the related autobumped Conda version.

Could that be synced in an upcoming minor (1.3) oder patch (1.2.4) release?

**Comment by oschwengers** [comment]
Thanks for releasing `1.2.4`!
Unfortunately, `__version__ = 1.2` in `__init__.py` is still out of sync with the GH/Conda release `1.2.4`.
This prevents fine-grained version controls (e.g. regarding https://github.com/BolognaBiocomp/deepsig/issues/28) for the integration of DeepSig into larger pipelines and tools like for example [Bakta](https://github.com/oschwengers/bakta/issues/32).

https://github.com/BolognaBiocomp/deepsig/blob/700fd43ea5a8e25d3a3c97822c5429e680f3c8a3/deepsig/__init__.py#L1

Would it be possible to patch this by a version bump of `deepsig/__init__.py.__version__` to, e.g. `1.2.5` with a subsequent synced GH/Conda patch release `1.2.5`?

**Comment by savojard** [comment]
Done!

**Comment by oschwengers** [comment]
Thanks a lot!!!
